denoland/manual

testing/documentation.md
Tracking the changes introduced in https://github.com/denoland/deno/pull/11438
=> Document inferred media types for fenced code blocks

getting_started/command_line_interface.md, getting_started/debugging_your_code.md, getting_started/first_steps.md, getting_started/installation.md, getting_started/permissions.md, getting_started/setup_your_environment.md, getting_started/webassembly.md, introduction.md
Read thru the "Getting Started" section and cleaned it up here and there.
=> polish up Getting Started section

runtime/http_server_apis.md
Closes https://github.com/denoland/manual/issues/23
=> docs for native server side websocket

npm_nodejs/cdns.md
=> fmt with latest canary

examples/http_server.md, runtime/http_server_apis.md
=> Update chapters for Deno.serveHttp stabilization

getting_started/permissions.md, runtime/http_server_apis.md, runtime/workers.md
Closes https://github.com/denoland/manual/issues/46
Closes https://github.com/denoland/manual/issues/47
=> Update manual for Deno 1.13

getting_started/setup_your_environment.md
Fixes https://github.com/denoland/manual/issues/56 .
=> Add Nova editor setup instructions

linking_to_external_code/private.md
=> Add documentation about Basic auth

runtime/http_server_apis.md
Closes https://github.com/denoland/manual/issues/82
=> Add documentation about stable Deno.upgradeWebSocket

tools/formatter.md, tools/linter.md, tools/repl.md
=> tools: update linter, formatter and REPL

runtime/ffi_api.md
Unified the variable name for the library extension and 
added logging of the result to show the example working.
=> [ FFI ]: ( Fix | Library Suffix ) ( Addition | Displaying Result )

testing.md
Added link to [fast-check](https://dubzzz.github.io/fast-check.github.com/) property based testing library to the 'Integration with testing libraries' section in testing.md.
=> Add fast-check link to testing.md

runtime/web_platform_apis.md
=> add information about local file fetch

jsx_dom.md, jsx_dom/jsx.md, toc.json
Including information about the JSX import source.
=> add documentation about JSX

examples/http_server.md
Use new std/http API.
Ref: https://github.com/denoland/deno_std/pull/1506
=> fix(examples): new std/http API

contributing/release_schedule.md
=> Update release schedule

examples/file_server.md
* Fixed server hang after the first request
* If request results in a directory, try to find a index.html file in that directory
=> Fixed file streaming examples

getting_started/setup_your_environment.md
Adding some instruction here on how to resolve having two active clients in a Node or Deno project.
As mentioned here in https://twitter.com/ja153903/status/1460699721610280973
=> Adding note about resolving multiple active LSP clients (denols and tsserver) in Neovim

examples/os_signals.md
Closes https://github.com/denoland/manual/issues/168
=> Update OS signal example

testing.md
based on https://github.com/denoland/deno/discussions/12603#discussioncomment-1711677
=> docs: add `sinon` spy example

examples/http_server.md
This PR will address some updates to the standard library.
https://github.com/denoland/deno_std/pull/1648
https://github.com/denoland/deno_std/pull/1660
=> chore: update std http server example

contributing.md, tools/documentation_generator.md
Fixes https://github.com/denoland/manual/issues/183
=> Fix links to doc.deno.land

runtime/http_server_apis.md
Just noticed a small typo in this example.
=> Fix typos in http server stream example

runtime/permission_apis.md
add info about PermissionDescriptor type
=> docs: update Permission APIs

testing.md
=> testing: update overload add test steps API example

getting_started/debugging_your_code.md
Ref https://github.com/denoland/deno/issues/12417
=> Add note about debugging short programs

getting_started/setup_your_environment.md
[vim-easycomplete](https://github.com/jayli/vim-easycomplete) support deno done.
=> feat: update deno ide environment,  using vim-easycomplete for deno lsp

testing/coverage.md
=> docs(coverage) update coverage manual with '--output' option for writing 'lcov' report

testing/assertions.md
Document https://github.com/denoland/deno_std/pull/1906
=> docs(testing): document `assertAlmostEquals`

runtime.md, runtime/http_server_apis.md, runtime/web_platform_apis.md
I also restructured some of the Web API stuff so that it all works a bit better.
=> add information about automatic body compression

examples/subprocess.md
Resolves https://github.com/denoland/deno/issues/10399#issuecomment-830920260
=> docs(subprocess): demonstrate windows "echo hello"

webassembly.md
=> fix: update broken link

contributing/building_from_source.md
See https://github.com/denoland/deno/pull/13928
=> contributing: Add `lld` prerequisite for apple silicon users

toc.json, tools.md, tools/task.md
=> Add `deno task`

testing/assertions.md
See https://github.com/denoland/deno_std/pull/2028
=> docs(testing): document `assertInstanceOf`

node.md
I was reading the manual with the [Grammarly](https://app.grammarly.com/) extension and it suggested these changes 😆
=> docs(node): Move comma

tools/task_runner.md
=> task_runner.md: remove stray whitespace

runtime/web_platform_apis.md
=> conjugate correctly

language_server/overview.md, vscode_deno.md
Ref: denoland/vscode_deno#633, denoland/vscode_deno#635, denoland/deno#13978
=> add information about deno.enablePaths

node.md
=> :bug: (bug): Fix broken links on node section

.github/workflows/ci.yml
https://github.com/actions/checkout#checkout-v3
Similar to https://github.com/denoland/deno/pull/14089
=> Move actions to actions/checkout@v3

node/cheatsheet.md
https://github.com/denoland/deno/pull/13713
=> deno bench was added

examples/http_server.md
remove comma and modified to match the above example code
=> fix(examples): modified to match the above example

getting_started/setup_your_environment.md
This reverts commit 475985f64c0aac0e4c8849778e773d019d7bfd02.
ref #289
=> Revert "add doc for DENO_NO_PROMPT (#289)"

getting_started/setup_your_environment.md
retry of #289
should be landed after https://github.com/denoland/deno/pull/14209 landed
=> add doc for DENO_NO_PROMPT

testing/assertions.md, testing/snapshot_testing.md
Adds documentation for https://github.com/denoland/deno_std/pull/2039
=> add documentation for snapshot testing

tools/benchmarker.md
=> Update benchmarking section with new report

toc.json
Fixes https://github.com/denoland/manual/issues/299
=> fix: add 'Snapshot testing' to toc.json

jsx_dom.md
Fixing part of https://github.com/denoland/dotland/issues/2128.
=> docs(jsx_dom): Fix "Using deno-dom with Deno" link

getting_started/configuration_file.md
https://github.com/denoland/deno/pull/14555
=> Add information about --no-config flag

getting_started/setup_your_environment.md
This is a follow up to https://github.com/neovim/nvim-lspconfig/pull/1933
I have made the changes required by https://github.com/neovim/nvim-lspconfig/pull/1933, removed redundant information and improved the quality of the technical writing.
=> Rewrite Vim and Neovim sections + grammar and spelling corrections

contributing/style_guide.md, testing/assertions.md
I'm reading through the docs and source code, and I'm hoping to make more substantial contributions in the future.
=> Documentation nit fixes

examples/os_signals.md
=> Deno 1.23 - SIGINT and SIGBREAK listening is available on Windows

tools/repl.md
https://github.com/denoland/deno/pull/14536
=> Document repl new key binding(ctrl+s)

runtime/permission_apis.md
Fell out of date as of https://github.com/denoland/deno/pull/12159.
=> Update permission revoke behavior

getting_started/configuration_file.md
#304 didn't update old text about the planned feature. Also reworded a bit to make it more natural.
=> Update note about configuration file auto-detection

tools/vendor.md
=> Fix typo in vendor.md

getting_started.md
=> fix: update getting started link

.github/workflows/suggest-format.yml, README.md
close #371.
See https://github.com/ayame113/manual/pull/1#discussion_r933066551 for how this works.
=> ci: suggest to format the code in the pull request

contributing/style_guide.md
ref: https://github.com/denoland/deno_std/pull/2359
add section for naming conventions
=> add section for naming conventions

tools/compiler.md
This was requested in https://github.com/denoland/deno/issues/10693#issuecomment-1217178757
=> Mention unavailable Web Storage API in compiled executables

tools/task_runner.md
Docs for https://github.com/denoland/deno/pull/16110
=> `deno task` - `INIT_CWD` section

examples/read_write_files.md
This page appears second in Google results for "append to file deno" but doesn't have an append example. Please feel free to close this pull request or make edits if you think `append` should be explained/added to this doc in a different way.
=> Add `append: true` example for writing text

README.md
This PR documents how to start local dotland with local manual contents. closes #3
=> docs: document dev command

references.md
Changed `STD_VERSION` to `CLI_VERSION`
=> fix broken link in references

node/how_to_with_npm.md, node/how_to_with_npm/express.md, node/how_to_with_npm/react.md, node/how_to_with_npm/vue.md, toc.json
=> Npm updates

basics/permissions.md
for https://github.com/denoland/deno/pull/16765
=> update --allow-ffi docs

introduction.md
=> fix: link correctly to std in introduction.md

runtime/builtin_apis.md
`https://deno.land/api@vv1.28.3?s=Deno` -> `https://deno.land/api@v1.28.3?s=Deno`
=> fix: version url update builtin_apis.md

examples/fetch_data.md
In the fetch data paragraph, switch to using `file.writable` instead of `writableStreamFromWriter`. This simplifies the code.
=> Update fetch data example

advanced/deploying_deno.md, advanced/deploying_deno/kinsta.md, runtime/http_server_apis.md, tools/repl.md
A guide explaining how to deploy Deno apps to Kinsta App Hosting
=> Deployment guide for Kinsta Application Hosting

basics/connecting_to_databases.md
Used a now-defunct email address to sign the commit used in https://github.com/denoland/manual/pull/474, so the CLA bot won't approve the PR even though I have signed the CLA. Creating a new PR where the CLA bot will hopefully work properly with a non-defunct email address.
Sorry for the inconvenience, maintainers.
=> Rewrite some sections of Connecting Databases for readability (take 2)

examples/subprocess.md
Fixes https://github.com/denoland/manual/issues/500
=> Don't block with await p.status() called first

webgpu/webgpu-experimental.md
=> #188 webgpu

node/how_to_with_npm/express.md
Add @deno-types to express server example.
=> add express @deno-types

getting_started/setup_your_environment.md
Closes #532 
before this, `tsserver` would run in single file mode and conflict with denols anyways
=> fixed incomplete neovim lsp setup solution

getting_started/configuration_file.md
This PR fixes some of the configuration file page grammar and spelling.
=> Fix configuration file page grammar

getting_started/first_steps.md
=> fix: unused variable warning in first steps

getting_started/first_steps.md
Small changes to the First Steps doc:
- Fix grammar issues
- Add instruction to create `http_server.ts` file (similar to creating `first_step.ts` file in the beginning of tutorial)
=> chore: update first steps doc

runtime/ffi_api.md
Changed the pointer type and added some information about it.
Also some other minor improvements.
=> Update FFI manual after Deno 1.31

basics/permissions.md
docs: fix bold style for allow-ffi permission
=> docs: fix bold style for allow-ffi permission

examples/unix_cat.md, getting_started/first_steps.md
=> Fix file cat example

getting_started/installation.md
https://ports.macports.org/port/deno/
=> docs(installation): add MacPorts install info

examples/hashbang.md
- Clear unnatural wording in Overview
- Remove outdated pending hashbang issue
- Change Permissions from Linux -> Unix (Mac/Linux/Friends)
=> Clean up wording in hashbang example

examples/subprocess.md
Fix https://github.com/denoland/manual/issues/597
=> Subprocess example update with Deno.Command

node/npm_specifiers.md
I couldn't find any documentation for this anywhere except for [this comment](https://github.com/denoland/deno/issues/17930#issuecomment-1445150560).
=> Document --node-modules-dir=false

getting_started/configuration_file.md
Ref https://github.com/denoland/deno/pull/19102
=> Glob support in configuration file

references/contributing.md
See the last point in https://github.com/denoland/fresh/pull/1233#issuecomment-1586042446.
=> docs: Puppeteer installations instructions for contributing to Fresh

references/contributing.md
Fixes https://github.com/denoland/fresh/pull/1233#issuecomment-1590486475
=> docs: fix typo in submitting PR to Fresh section

references/contributing.md
Fix a few minor grammar nits. Bubble Fresh higher in the repository listing.
=> chore: Contributing overview tweaks

runtime/http_server_apis.md
Closes https://github.com/denoland/deno/issues/19306
=> Update documentation for HTTP server APIs

references/contributing.md
See https://github.com/denoland/fresh/pull/1573
=> docs: update Fresh contributing section to mention `deno task ok`

runtime/kv/key_space.md
=> docs: "ULIDs" section tweaks

runtime/web_platform_apis.md
=> web: Add note about Event.timeStamp being 0

.gitignore, node/migrate.md, references/contributing.md, toc.json
Starting up a migration doc which we can iterate on over time. Included some of the higher-level differences in a single place.
=> MVP migration doc

basics/testing/snapshot_testing.md, examples/module_metadata.md, node/how_to_with_npm/express.md, node/how_to_with_npm/react.md, node/how_to_with_npm/vue.md
This PR updates code formatting using the latest stable deno
=> chore: format code examples
