denoland/manual

.github/workflows/ci.yml

This is implicitly the default.

chore: remove `github.ref` in ci.yml 

---

getting_started/command_line_interface.md

Removed UNSTABLE since --import-map is stable now

fix(manual): import-map is stable

---

testing/sanitizers.md

Without `../`, the link goes to the 404 page.
https://deno.land/manual@v1.12.2/testing/sanitizers#resource-sanitizer

docs(sanitizers): fix link to architecture doc

---

runtime/http_server_apis.md

When trying out the new (amazing) HTTP interface of Deno, I found a mistake in the documentation:
The example of the handle function does not work, as URL provides the path via the `pathname` attribute, not `path`.
[MDN docs on the topic](https://developer.mozilla.org/en-US/docs/Web/API/URL)
Thanks for your amazing work on the manual 🙇

HTTP: Fix the handle function example

---

getting_started/setup_your_environment.md

Documents the variable `DENO_TLS_CA_STORE` 
- Depends on https://github.com/denoland/deno/pull/11491

feat(tls): Add DENO_TLS_CA_STORE documentation

---

npm_nodejs/std_node.md

```
deno doc https://deno.land/std/assert.ts
Download https://deno.land/std/assert.ts
Warning Implicitly using latest version (0.105.0) for https://deno.land/std/assert.ts
Download https://deno.land/std@0.105.0/assert.ts
The graph is missing a dependency.
Specifier: https://deno.land/std/assert.ts from file:///Users/.../$deno$doc.ts
```
➜  deno doc https://deno.land/std/assert.ts     
-> 
➜  deno doc https://deno.land/std/node/assert.ts

fix doc "deno doc std node assert" command typo

---

examples/subprocess.md

When using double quotes inside single quotes raises this error:
Leaving only one of them solves the issue:

Update Deno.run when running commands with bash shell.

---

examples/http_server.md

Relates to https://github.com/denoland/deno_std/discussions/1034 and https://github.com/denoland/deno_std/pull/1128.
Updates the `http_server` example to use the new std/http "native" server APIs.

docs(examples): update `http_server` example to use new native server APIs

---

contributing.md

fix(docs): add mailto markdown syntax to email link

---

getting_started/setup_your_environment.md

Very small change to fix a typo in the docs. 
The correct setting to enable deno in Visual studio code is `deno.enable`, not `deno.enabled`
I spent several minutes trying to understand what was wrong with my vs code, but then I realised that it was just a typo in the docs. I hope this can help someone else!

docs: fix a typo in the setup environment doc

---

tools/formatter.md

This would describe to users at a glance what file types are supported and how the formatter matches those file types.
I do not know if this list is correct, but I came to this page expecting this information to be shared.

docs: deno fmt list of files & how they are matched

---

getting_started/permissions.md

- Minor typos corrected for better consistency
- Also, slightly adjusted the wording for `--allow-all` flag. It may be better left as is, I just personally found the phrase "disable all security" strange.

fix(doc): Correct typos and adjust allow-all flag explanation

---

tools/dependency_inspector.md

This updated the `deno info` output in the manual example to reflect the changes made in https://github.com/denoland/deno/pull/11989

fix(docs): update displayed deno info property names

---

tools/linter.md

The current link brings us to https://deno.land/manual@v1.14.1/configuration_file, which is 404 not found. The correct target should be https://deno.land/manual@v1.14.1/getting_started/configuration_file.

docs(lint): fix link to configuration_file.md

---

tools/dependency_inspector.md
typescript/configuration.md

This fixes not one, but two whole typos in the manual.
:)

fix(docs): update two typos

---

getting_started.md

fix(docs): remove WebAssembly link from Getting Started chapter

---

toc.json

mostly a grammatical nit: "Setup your environment" -> "Set up your environment" to match [this page heading](https://github.com/denoland/manual/blob/5391d1435c150e051b585b61dcf0823503587a4e/getting_started/setup_your_environment.md?plain=1#L1)

Update TOC to match page heading

---

examples/os_signals.md

`Deno.signal` enum was removed in https://github.com/denoland/deno/pull/11909, but the examples still use it. This updates the examples to use the `Signal` union type that replaced the enum.

fix(docs): update os signals example to the latest Deno.signal API

---

testing.md
testing/assertions.md

Closes #107 
Should be merged after `deno_std` 0.111.0 is released, because links don't work right now.

testing: add example for Chai and Sinon

---

getting_started/setup_your_environment.md

The old link to the Neovim nightly was only temporary until https://github.com/neovim/neovim/issues/15709 was closed.

fix(docs):update the URL for downloading neovim nightly

---

getting_started/setup_your_environment.md

The manual refers to "ASCII color codes". ASCII does not contain any control codes
related to color. Instead it is [ANSI codes](https://en.wikipedia.org/wiki/ANSI_escape_code)
which relate to color on the terminal. Correct the use of "ASCII" to "ANSI".

getting_started: fix "ASCII" -> "ANSI"

---

tools/repl.md

The line `> > const foo = "bar";` throws `parse error: Expected ';', '}' or <eof> at 1:9` because of a duplicate `>`

chore: remove duplicate angular bracket in repl.md

---

examples/fetch_data.md
examples/file_server.md

Closes #133 
Changes:
- Add a section about files and streaming to the [Fetch Data example](https://deno.land/manual@v1.16.0/examples/fetch_data).
- Rewrote the [File Server example](https://deno.land/manual@v1.16.0/examples/file_server) to explains how people can write their own file server from scratch. 
I tried to keep the file server example as simple as possible, but it may be missing some exception handling. Should I add it?

Add file streaming examples

---

vscode_deno.md

Visual Studio Code workspace settings file name should be `settings.json` instead of `setting.json`.
https://code.visualstudio.com/docs/getstarted/settings

fix(docs): vscode settings file name

---

examples/unix_cat.md

The `copy` function from `std/io/util.ts` was deprecated with the recommendation to use `std/streams/conversion.ts` instead. This updates the Unix `cat` example in the manual accordingly.

chore: update deprecated function in unix cat example

---

linking_to_external_code.md

`assertStrContains` was removed a while ago in place of `assertStringIncludes`

fix: update import name to assertStringIncludes

---

getting_started/setup_your_environment.md

In `setup_your_environment.md`, https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md is moved to https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md now.

fix(docs): fix link in setup_your_environment.md

---

getting_started/setup_your_environment.md

Starting with WebStorm 2021.3 (and the corresponding versions of other IDEs), the Deno plugin uses the LSP ([WEB-48625](https://youtrack.jetbrains.com/issue/WEB-48625)).
Additionally, it uses the output of `deno types` instead of the bundled file.
You may want to wait with merging until WebStorm 2021.3 is officially released, that's why I created the PR as a draft.

Update JetBrains section in "Set up your environment"

---

examples/tcp_echo.md
getting_started/first_steps.md

`copy` from `io/util.ts` was deprecated in favor of `copy` in `streams/conversion.ts`

chore: update examples to use non-deprecated copy function

---

runtime/permission_apis.md

fix small typo in manual/runtime/permission_apis.md
The use of "no longer" vs "not longer" is debatable but in this context, I think the better option for readability is "no longer" since it is followed by an adjectivized verb.

fix docs(permission_apis.md): small typo

---

getting_started/setup_your_environment.md

Neovim 0.6 has been released, so no need anymore to mention the need to use pre-release builds

chore: update documentation for neovim

---

language_server.md
language_server/imports.md
language_server/overview.md
toc.json

~~Blocked by denoland/deno#13023~~

migrate lsp docs to manual and update for v2 registry completions

---

npm_nodejs/std_node.md

Fixing the current 404 error in the production manual on https://deno.land/manual@v1.16.4/npm_nodejs/std_node

Fixed link with redundant npm_nodejs path

---

runtime/ffi_api.md

As the `buffer` type was renamed to `pointer` in v1.17.0.

fix(runtime/ffi_api): change `buffer` type to `pointer`

---

continuous_integration.md

I forgot to change one of the occurrences of `experimental` to `canary` . Also noticed I didn't add a filename argument to the `deno cache` command

fix: update keyword and add filename to cache command

---

getting_started/permissions.md

The use of "irregardless" is nonstandard and can be confusing, see https://www.merriam-webster.com/dictionary/irregardless.

Change nonstandard wording in permissions docs

---

testing/assertions.md

per https://github.com/denoland/deno_std/pull/1646 and https://github.com/denoland/deno_std/issues/1562 assertThrowsAsync has been removed, thus updating the manual

remove assertThrowsAsync in favor of assertRejects

---

testing.md
testing/coverage.md

Closes https://github.com/denoland/manual/issues/198
Updates testing and coverage chapter to show proper globs.
Adds note about coverage data getting out of sync.

Update testing and coverage chapters

---

testing.md

I removed the mention of `describe`/`it` style testing because the test steps are different from that. Most of the documentation I added here is inline by example.

Update test step docs now that it's stable

---

npm_nodejs.md
npm_nodejs/compatibility_mode.md
npm_nodejs/std_node.md

Change different spellings of `compatibility` to the correct spelling.

Fix 'compatibility' with Node.js/npm

---

typescript/configuration.md

Closes #216 
From [#11826](https://github.com/denoland/deno/issues/11826), `useUnknownInCatchVariables` is default `false` in Deno.

docs(configuration): add missing row for `useUnknownInCatchVariables`

---

npm_nodejs/cheatsheet.md

Right now the underscores are not handled properly and showing up in the manual page: https://deno.land/manual@v1.18.1/npm_nodejs/cheatsheet

fix unprocessed markdown syntax

---

examples/os_signals.md

Changed `existing` to `exiting` in line 41 and 94.
`setTimeout` is called to keep the program from exiting but not to delay existence.

Fixed potential typing mistake

---

examples/os_signals.md

https://deno.com/blog/v1.19#stabilization-of-signal-listener-apis

chore: unstable flag no longer needed for OS signals

---

runtime/program_lifecycle.md

The current code examples for program lifecycle violate [one of the recommended rules from deno lint](https://lint.deno.land/#no-window-prefix), so I updated them to comply with the linter.

docs(lifecycle): avoid window per deno lint

---

examples/subprocess.md

After getting this answer this from the Deno discord, I figured I should do my part and share it since it's pretty basic functionality.
The one reason I think this PR might be rejected is because the example includes imports from std instead of purely using the built-in API.

Subprocess Info/Example for piping

---

runtime/ffi_api.md

The C example file is refered as `// add.c`, but the commands compilations examples use `add_numbers.c` instead.
Additionally, the `.ts` use `libadd` as lib path so it doesn't work out of the box when you try it 
Also `-Wl` may be a typo because it throws the following:
```ts
cc: error: unrecognized command line option ‘-Wl’; did you mean ‘-W’?
```
Just using `-W` is fine though

fix(runtime/ffi_api): wrong paths for C examples

---

testing/sanitizers.md

I think the sample code in testing/sanitizers.md is different.
Resource sanitizer is `setTimeout` and Op sanitizer is `Deno.open`.

Fix "Test sanitizers" sample code

---

typescript/configuration.md

Analogs are great if the audience is guaranteed to have the requisite context, else they become an additional barrier to understanding.

docs: replace colloquial analog with literal description

---

getting_started/setup_your_environment.md

Nitpick from: ['Couple,' 'Few,' and 'Several': The (Mostly) Definitive Guide](https://www.merriam-webster.com/words-at-play/couple-few-several-use)
> Couple is used when referring to two things, as in "a couple of days ago," whereas few and several are less specific. Few means "not many but some," as in "The train leaves in a few minutes," and several denotes more than the words couple and few do but implies lesser than the word many does.

docs(setup): Minor edit

---

continuous_integration.md

https://github.com/actions/checkout#checkout-v3
Similar to https://github.com/denoland/deno/pull/14089

Move CI docs from actions/checkout@v2 to v3

---

runtime/http_server_apis.md

This could also be:
```js
({ response, socket }  = Deno.upgradeWebSocket(req));
```
But that form of destructuring assignment might be less familiar to users

fix: typo in Deno.upgradeWebSocket example

---

examples/manage_dependencies.md
jsx_dom/css.md
jsx_dom/jsdom.md
jsx_dom/jsx.md
jsx_dom/linkedom.md

`ts ignore` works to exclude a block from type-checking but the site's markdown parser expects `ts, ignore`, otherwise the syntax highlighting will be missing: https://github.com/lucacasonato/deno-gfm/blob/5445765933f9db0fc019e824bfe0eef2fa3d109e/mod.ts#L18

fix: update ignore attrs to enable syntax highlighting

---

introduction.md

I fixed this issue to make the sentence corresponding with https://deno.land/manual@v1.12.2/introduction

Fix broken sentence in intro #266

---

runtime/http_server_apis.md

The documentation for the ReadableStream example is broken and doesn't return anything.  This change corrects this with the correct handling of the body, piping it through the TextEncoderStream.

doc: fix ReadableStream http server api example

---

testing/behavior_driven_development.md
testing/mocking.md
toc.json

I created these new pages from the documentation in https://deno.land/std@0.135.0/testing/README.md. The only difference is one less `#` for each heading.

docs(testing): behavior driven development and mocking

---

getting_started/setup_your_environment.md

https://github.com/denoland/deno/pull/14209

add doc for DENO_NO_PROMPT

---

examples/file_server.md

Closes https://github.com/denoland/manual/issues/286
This is the fast path we are optimizing for in https://github.com/denoland/deno/pull/14284 (benchmark numbers are going to go up once it relands)
Also, removes the directory -> index.html handling... it's not really useful. best to defer to the optimized std/http/file_server for complex stuff.
`sample.txt` = 5MB
Earlier:
```
wrk -t8 -c20 -d10s http://localhost:8080/sample.txt
Running 10s test @ http://localhost:8080/sample.txt
8 threads and 20 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    86.02ms    4.50ms 128.32ms   91.77%
Req/Sec    23.30      7.36    40.00     84.00%
1872 requests in 10.10s, 9.18GB read
Requests/sec:    185.35
Transfer/sec:      0.91GB
```
This PR:
```
wrk -t8 -c20 -d10s …
```

chore(examples/file_server): use fast path for streams

---

publishing.md
vscode_deno/testing_api.md

I spotted two small typos in `testing_api.md` and `publishing.md`.

Fix Small Typos

---

runtime/workers.md

This is a somewhat common pain point which is not a bug, so it should be documented in the manual.
Closes #264.

Note not to use TLA in workers before setting the `message` listener

---

runtime/ffi_api.md

All ELF platforms (*BSD, solaris/illumos) use .so for libraries. Let's not teach people to hardcode Linux.

docs(runtime): in the FFI example, do not hardcode 'linux' for .so

---

contributing/style_guide.md

This was first suggested in this issue https://github.com/denoland/deno_std/issues/1649
Since most of us seem to prefer `#` over `private` keyword, I suggest we set this as an explicit rule.

docs: add style guide about private fields

---

jsx_dom.md

Fixing part of https://github.com/denoland/dotland/issues/2128.

docs(jsx_dom): Fix "Using LinkeDOM with Deno" link

---

introduction.md

While @lambtron, @crowlKats, and I were discussing discoverability of documentation, we realised that our introduction and feature highlights didn't really link into the rest of the manual as it should.  This updates some of the copy and provides good links into the rest of the manual to allow users to better discover Deno.

Improve feature highlights in introduction

---

runtime/http_server_apis.md

This makes the `A "Hello World" server` link clickable

fix(manual): Remove quotes from header link

---

testing/snapshot_testing.md

Adds docs for https://github.com/denoland/deno_std/pull/2179 and documentation for use of "Deno.customInspect" with "assertSnapshot"

Add docs for options and use custom inspect with "assertSnapshot"

---

runtime/ffi_api.md

Fixes this issue https://github.com/denoland/deno_doc/issues/253

fix issue with code sample in ffi for compiling add.c in windows

---

runtime/compiler_apis.md
typescript.md

Fixes #326
The page was linking to a page that was removed as part of #319.
Edit: already removed from TOC

fix: remove invalid link to compiler APIs page

---

tools/task_runner.md

Was writing the blog post and realized I forgot to put this in the manual.

Add docs on task appending redirects

---

runtime/ffi_api.md

Pointers are represented by `bigint`s now
https://github.com/denoland/deno/pull/14915

Update note for FFI pointers

---

runtime/ffi_api.md

Relates to https://github.com/denoland/deno/pull/14663

Add Callbacks portion to FFI API manual

---

introduction.md

Now it properly takes you to the https://deno.land/std/ instead of showing this:
```
Bad Request
Bad request: Module not found "https://deno.land/std@0.146.0".
```

fix: link not pointing to the right location

---

testing/snapshot_testing.md

Adds documentation for https://github.com/denoland/deno_std/pull/2403

Add docs for createAssertSnapshot

---

getting_started/configuration_file.md
introduction.md
linking_to_external_code/import_maps.md

Adding this to the manual so others don't have to read the JSON schema of config file in order to realize the existence of `importMap` option like me.
Also improved the links in Introduction page for GitHub a little bit.

Add note about `importMap` option in config file

---

getting_started/command_line_interface.md
getting_started/setup_your_environment.md

Issue: https://github.com/denoland/manual/issues/348
This PR updates the `getting_started` section to incorporate changes from **v1.23** regarding type-checking by default.

docs(getting_started): Add subsection for type-checking instructions

---

introduction.md

Fix some links in Introduction page so they point to the correct files on GitHub. After https://github.com/denoland/dotland/pull/2177 is merged there will also be zero redirect penalty.
From https://github.com/denoland/manual/pull/333#discussion_r913211947

Fix Introduction links on GitHub

---

tools/benchmarker.md

If I’m not mistaken, the ignore flag should be reversed.
If `Deno.build.os === 'windows'`, the bench should run, not be ignored.

fix: ignore if os isn’t windows

---

node/compatibility_mode.md

This section is a duplicate of https://github.com/denoland/manual/blob/c0db8a49e2f43d17279b8532fdb8340e52217315/node/std_node.md#node-built-in-modules and seems outdated (worker_threads isn't anymore partial)

Remove duplicate section `Node built-in modules`

---

toc.json

This example was added in https://github.com/denoland/manual/pull/347 but it was not added to the TOC, so it does not show up in the Examples section in the sidebar on https://deno.land/manual.

fix: include shebang example in toc.json

---

runtime/ffi_api.md

I assume since the repo is now at denoland/deno_bindgen it's now the officially supported tool

Update deno_bindgen docs to reflect repo move

---

toc.json

I did not find any information about the flame graph in the official documents(https://deno.land/manual).
I think it's necessary to expose the profiling page.

docs(toc): expose the profiling page

---

.github/workflows/main.yml
continuous_integration.md

This bumps the versions of the Actions runners to:
- Ubuntu 22.04, [now generally available](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/)
- MacOS 12
- Windows Server 2022

chore: update ci runner versions

---

runtime/ffi_api.md

The current manual documentation does not yet reflect the breaking change made in release [v1.25.0](https://github.com/denoland/deno/releases/tag/v1.25.0) that split the pointer type into pointer and buffer. See denoland/deno#15518 for more information.
Co-authored-by: duart38 <duartsnel@icloud.com>
Signed-off-by: David Greven <opensource@grevend.dev>

Update manual based on FFI breaking change in v1.25.0

---

runtime/ffi_api.md

C# and Kotlin are not great recommendations. While both may technically be capable of creating shared libraries, it's not really along the "happy path" for either one. Experimental, very early stages, etc.
Nim is probably a more reasonable suggestion, but is *very* niche, and I know its got some weird complexity around "it's kind of garbage collected" but also "it supports manual memory management".
I think trimming it down to C, C++, Rust, and Zig provides a good number of candidates that actually have well documented support for creating shared libraries and making use of the C ABI.

docs: remove weird language suggestions from FFI page

---

vscode_deno.md

This PR aims to add documentation for https://github.com/denoland/vscode_deno/issues/715 since it's not well explained in any places I've searched before and it's such a simple issue to fix.

doc: Add new section to troubleshooting in VSCode Deno due to recent issue

---

contributing/building_from_source.md

There is no sample code to run after build.
I expected it to be a git submodule related issue, but apparently the file doesn't exist.
It would be good to change the sample code to check if it is executable
```sh
:) % ./target/debug/deno run cli/tests/testdata/002_hello.ts
error: Module not found "file:///Users/asan/lab/oss/deno/cli/tests/testdata/002_hello.ts".
```
- I change sample code. `cli/tests/testdata/002_hello.ts` to `https://deno.land/std/examples/welcome.ts`
- Please let me know if there is anything else suitable.

docs: Update document building_from_source

---

continuous_integration.md

This updates the Deno GitHub action in the CI chapter to 1.1.1, which uses a non-deprecated version of Node.

chore: update setup_deno action version

---

.github/workflows/check-links.yml
.github/workflows/ci.yml
basics/standard_library.md
getting_started/command_line_interface.md
runtime.md
runtime/stability.md

The link checker has been failing in a number of PRs lately. I found one link was actually broken because it was moved within denoland/deno, while other links are a bit flaky: broken in CI but available when visited in a browser. Therefore, as a suggestion I have moved the link checker to a separate workflow that runs on a schedule daily. This way it does not get in the way of PRs.
Edit: also fixes #480

chore: fix broken links and move link checker workflow to schedule

---

getting_started/setup_your_environment.md

Related to: https://github.com/denoland/deno/issues/16105
I think there is probably more work to do to flesh out support for private registries (e.g would be great to formalize things like [auth configuration](https://docs.npmjs.com/cli/v9/configuring-npm/npmrc#auth-related-configuration)) but this at least documents a way to start integrating with a private registry.

Add `NPM_CONFIG_REGISTRY` to environment docs

---

node/how_to_with_npm/prisma.md

Hi!
This PR fix a typo in how_to_with_npm/prisma.md`

fix(typo): Fix typo in `how_to_with_npm/prisma`

---

getting_started/command_line_interface.md
getting_started/setup_your_environment.md

Fixes #456. Atom will continue under the name Pulsar, some links to the Atom website also needed fixing.

chore: update Atom paragraph

---

basics/modules/import_maps.md

This tripped me up as a new user to Deno, and I just helped someone in the Discord server w/ the same misunderstanding.
I think people see import map and think it works transitively like package.json. Pointing people in the right direction here can save a lot of headaches. :)

Note the limited scope for Import Maps

---

examples/hashbang.md

Add a note in the help for creating a hashbang file, aka shebang file, to end the name of the file with the `.ts` when the file's source is TypeScript. The deno cli uses the file name extension for deciding TypeScript over JavaScript.
Future plans include supporting the command-line option `--ext <type>`, relieving this naming restriction. See [denoland/deno#5088](https://github.com/denoland/deno/issues/5088).

Add `.ts` info to hashbang.md

---

.github/.mlc_config.json
.github/workflows/check-links.yml

This page (https://kinsta.com/signup/) returns 403 to bot access, and we can't check it in `check-links` CI. This PR updates the ignore settings to avoid the error.

chore: update link check settings

---

tools/benchmarker.md

It looks like the examples for `Deno.bench` were pulled from the examples for `Deno.test` and a lot of the comments were left unchanged. This fixes that.

fix: typos in benchmarker

---

tools/linter.md

Updating deno_lint to the version including https://github.com/denoland/deno_lint/pull/1104 has a small change in its behavior. This commit updates the documentation regarding this change.
ref: https://github.com/denoland/deno/issues/17161

fix: lint's `--rules-exclude` now has higher precedence over `--rules-include`

---

examples/hashbang.md
toc.json

This was the old route. It seems we didn't add a redirect when renaming.
Also makes the text consistent with the title.

fix: add shebang redirect to hashbang

---

node/npm_specifiers.md

Fixed an invalid command line option `--A` in https://deno.land/manual@v1.29.1/node/npm_specifiers

Fix an invalid command line option

---

getting_started/command_line_interface.md

[Fig](https://fig.io) provides autocomplete for 300+ CLI tools including Deno. It looks like this:
We think this will help users become more efficient with Deno CLI, so we would love to have Fig listed as an autocomplete method in your docs. Thanks so much and please let me know if you have any questions!

Add Fig as an autocomplete method

---

runtime/ffi_api.md

This PR includes V:
https://github.com/vlang/v
with the other example languages in the FFI doc page.

Add V as example in docs

---

.github/.mlc_config.json
basics/env_variables.md

This PR updates the usage of `std/dotenv` module. ref: https://github.com/denoland/deno_std/pull/3134
also ignores `https://web.pulsar-edit.dev/` in link checks in CI as the pages under that domain now return 505 error responses.

docs: update std/dotenv usage

---

basics/connecting_to_databases.md

This fixes the capitalization of `DenoDB` to match the other spellings.

Fix DenoDB spelling

---

getting_started/first_steps.md

1. Removed step about writing response to file.
2. Removed the note about needing --allow-write permissions.
3. Remove the redundant 'Listening on http://localhost:8000' console.log (serve already logs this when called)
4. Capitalise 'H' in GitHub
Fixes issue [#464](https://github.com/denoland/manual/issues/464)

fix: Make HTTP server walk through consistent with code

---

advanced/deploying_deno/cloudflare_workers.md

1. Update denoflare version to 0.5.11
2. Fix local deployment script
Note: the denoflare v0.5.10 has an issue with the latest deno cli. When serving or pushing, it will throw an error. 
```
Deno.spawn is not a function
```

fix: outdated cloudflare deployment guide

---

basics/testing.md
tools/benchmarker.md

Although it's true that deno test/bench will find these files, it doesn't really make sense that it does. We should remove this from the documentation in order to not encourage it and consider deprecating this in the future.

Remove cjs and cts from test/bench glob documentation

---

examples/hashbang.md

Presumably the user owns the script file in question, so there's no earthy reason why they should need to run `chmod` with root permissions.

Docs: hashbang.md: Don't use sudo for chmod

---

examples/file_server.md

In the current example, 1 file miss causes the fileserver to break.
Because `return` is used, the code breaks out of the function, causing subsequent requests to fail.
By changing this to `continue`, the code continues to work as expected.

file_server: fix bug after file miss

---

advanced/continuous_integration.md

`lock.json` -> `deno.lock` to match up that lockfile name changes. 
see <https://deno.land/manual@v1.30.3/basics/modules/integrity_checking>

docs(advanced/continuous_integration): fix lockfile name

---

README.md
node/node_specifiers.md

A very small update to the contributing section, to make it clearer the user has to clone both repositories to be able to run `manual`.
I also had to update this broken link: https://github.com/denoland/deno_std/tree/main/node#deno-nodejs-compatibility
It looks like it was moved here, but please let me know if that's wrong: https://github.com/denoland/deno/blob/main/ext/node/polyfills/README.md

chore: update contributing instructions

---

tools/bundler.md

Currently the deprecation warning just suggests ESbuild as an alternative to `deno bundle`. `deno_emit` and Rollup are two other valid methods. 
This is also inline with the logged warning when calling `deno bundle` on latest (see: https://github.com/denoland/deno/blob/main/cli/tools/bundle.rs#L35)
Mostly helpful because `deno_emit` took me awhile to find but is exactly what I needed for a project I'm working on.

fix(manual) adds deno_emit and rollup to the list of 'deno bundle' alt

---

runtime/ffi_api.md

We'd apparently forgotten to add this feature, even though it already came out in January.

Add structs to FFI manual

---

.github/workflows/update-algolia.yml
.tools/deno.json
.tools/import-map.json
.tools/main.ts

This adds a ci that gets run whenever a tag is pushed, which updates the algolia search. follow up to #390.
also fixes the script to work with the latest verison of the manual

feat: add algolia update ci

---

runtime/workers.md

Hi! I couldn't find a canonical place explaining this better or the actual implementation but by testing it locally it seems that when setting the `net` permissions for workers it only allow strings containing domains and not full URLs which is the current example in the worker documentation.
Reading this [issue](https://github.com/denoland/deno/issues/5242) it seems that it's just domain indeed.
Maybe the most canonical place explaining this format is [here](https://deno.land/manual@v1.32.3/basics/permissions#permissions-list)

Update example of net permission for workers

---

tools/compiler.md

deno v1.32 adds support for dynamic imports and web workers
https://deno.com/blog/v1.32#deno-compile-support-for-web-workers-and-dynamic-import

docs: update compiler.md

---

basics/react.md

Hi! This PR fix a typo in `manual/basics/react.md`. Instead of two colons, there should be one.

fix(typo): Fix typo in `manual/basics/react.md`

---

basics/import_maps.md

From my understanding, the trailing slash is significant.

Fix scopes key in import map docs

---

getting_started/installation.md

While I'm not too sure either to recommend it as the [default way](https://github.com/denoland/manual/issues/393) to install Deno as asdf is not cross-platform, listing it in the documentation is a start.
Let me know if you want me to adjust other sections of the documentation.

Document install instruction using asdf

---

basics/permissions.md

While [updating the help text](https://github.com/denoland/deno/issues/18685) for the `--allow-sys` flag in the CLI, I noticed that it wasn't clear which APIs could be allowed when using this option. [This appears to be the list](https://github.com/denoland/deno/blob/main/runtime/permissions/mod.rs#L320) - I added this enumeration of function names to the docs here!
Preview:

Add allowed values for allow-sys flag

---

getting_started/command_line_interface.md

Unifies the examples for getting command-specific help to remove confusion. Replaces `bundle` with `compile`.

Remove references to deprecated bundle subcommand (fixes #574)

---

references/contributing/style_guide.md

This PR updates the naming convention of Deno Standard Library.
We don't mention the usage of UPPER_SNAKE_CASE in the style guide, but UPPER_SNAKE_CASE have been used in many places. That caused the discussion https://github.com/denoland/deno_std/issues/3331.
This change adds the description about the usage of UPPER_SNAKE_CASE in deno_std, and resolves the conflict between the style guide and the existing code.
closes https://github.com/denoland/deno_std/issues/3331

docs(style_guide): update standard library style guide

---

runtime/kv/transactions.md

Small typo in the `transferFunds` function in [runtime/kv/transactions](https://deno.com/manual@v1.33.0/runtime/kv/transactions).
Btw, the error seems a bit cryptic
```
error: Uncaught TypeError: Error parsing args at position 2: serde_v8 error: invalid type, expected: array
.commit();
^
at Object.opAsync (ext:core/01_core.js:256:30)
at AtomicOperation.commit (ext:deno_kv/01_db.ts:196:41)
at transferFunds (file:///path/to/file.ts:99:9)
at async file:///path/to/file.ts:9:9
```

docs: fix typo in `transferFunds`

---

runtime/kv/operations.md

The behaviour of `prefix` in `.list()` was logical, but was ambiguous in the documentation.
For a selector of `{ prefix: ["hello"] }` will not match `["hello"]` but will match `["hello", "world"]`.

Clarify kv.list prefix behaviour

---

runtime/kv/operations.md

This `await` in front of `kv.list` is flagged as unnecessary by typescript, and is not consistent with others example.

fix: remove await in front of kv.list

---

basics/modules/private.md

On the `Private Modules and Repositories` page, the example for specifying multiple authentication tokens has one semicolon delimiter and one comma delimiter.
This PR simply replaces the comma with a semicolon.

Replace comma delimiter with a semicolon

---

advanced/jsx_dom/deno_dom.md

Super tiny change. Nothing else to add here.

Remove unnecessary spacing in `deno-dom` doc

---

getting_started/configuration_file.md

The "semiColons" option was the only one missing from this list, so it was a little unclear if that option existed. In `manual/tools/formatter.md` we have the cli option `--no-semicolons`, while `deno/cli/tools/fmt.rs` accepts a "semiColons" option. The only place we specify that the "semiColons" option exists for the config file is in the full example below, but it's easy to miss. Since it's the only fmt option missing in this section, I thought it would be fine if we included it here too.

fix: Add 'semiColons' to 'fmt' example

---

tools/compiler.md

Based on [the Workers page of the manual](https://deno.com/manual@v1.34.1/runtime/workers):
> Workers can be used to run code on multiple threads. Each instance of Worker is run on a separate thread, dedicated only to that worker.
>
> Currently Deno supports only module type workers; thus it’s essential to pass the type: "module" option when creating a new worker.
>
> **Workers currently do not work in compiled executables.**
(emphasis mine)
If this is no longer the case, the Worker page should be fixed instead.

Add Workers to the "Unavailable in executables" section

---

node/faqs.md

b01345584887f6474e0bff6ab8cbf48a313726fb removed the "Getting errors when type checking like `cannot find namespace NodeJS`" section from the Node FAQ (since Deno 1.31 stabilized the Node-API[1]) but forgot to remove the subsections.
Fixes #677.
[1]: https://deno.com/blog/v1.31#stabilization-of-node-api

Remove left-over subsections about missing @types/node

---

basics/import_maps.md

This section of the manual seems to indicate that import mappings should be in a file called `import_map.json` and not `deno.json`, but the latter is what actually works in the runtime (without additional work). This updates those headings.

Update manual to indicate that import mappings should be in deno.json

---

getting_started/setup_your_environment.md

As I was reading the docs, I noticed a couple of missing apostrophes in this file; this corrects those.
While I was there, I also noticed a couple of sentences in the `Environment variables` section with potentially confusing wording (using double negatives, or roundabout passive voice), and decided we may as well tidy those up while we're here. (That's if the change is agreed upon as an improvement, of course.) :)

Add missing apostrophes and refactor a couple of sentences

---

basics/modules/private.md

- Corrects spelling of "may be"
- Corrects capitalization of GitLab and Bitbucket
- Other minor grammatical fixes and clarifications
Wasn't sure for line 22 if it was better to add the domain, or just delete the word "for." I chose the former, but the latter would work as well.

Minor typo and grammar fixes on Private Modules page

---

references/contributing.md

[dotland](https://github.com/denoland/dotland) is archived, so we can't contribute directly. Therefore, I have deleted this section

docs: remove dotland section

---

references/contributing/style_guide.md

It’s useful to have separate words for these concepts. I think this might have been intended to only apply to the folders within deno_std.

Internal style guide - Remove section on not using the word “library”

---

examples/file_server.md

[The example](https://deno.land/manual@v1.35.2/examples/file_server) suggests running the server with a global `--allow-read` permission, and the implementation simply appends the URL-decoded request pathname to '.' before reading whatever file is there.
By URL-encoding slashes as "%2F", an attacker can easily escape the current directory and ultimately read anything that the deno process can read in the whole filesystem by calling the file server (for example, "/..%2F..%2F..%2F.ssh/config" or however many times "../" is needed to backtrack to the user directory).
Thankfully, deno was designed to prevent this kind of exploit without even looking at the code. This PR just narrows `--allow-read` to the current directory to match what the code *seems to be doing*.

Prevent whole filesystem read exploit in file server example

---

references/contributing.md

Accompanies https://github.com/denoland/deno/pull/20048.

Add section on __runtime_js_sources

---

basics/permissions.md

Typo `--allow-net` in the v1.36 new flags list, should be `--deny-net`.

Fix typo in `basics/permissions.md`

---

references/contributing.md

"Additionally to" is an awkward construction in English, perhaps even non-grammatical.

Improved prose in contributing.md

---

advanced/jsx_dom/css.md
advanced/jsx_dom/deno_dom.md
advanced/jsx_dom/jsdom.md
advanced/jsx_dom/linkedom.md
basics/modules.md
basics/testing.md
basics/testing/assertions.md
basics/testing/behavior_driven_development.md
basics/testing/mocking.md
getting_started/configuration_file.md
references/contributing/style_guide.md
references/vscode_deno.md
tools/repl.md

Users copy-pasting testing code from the docs currently encounter a deprecation notice because of the moved assertions.
This fixes imports changed by https://github.com/denoland/deno_std/pull/3445.
Also closes #558.
Fixes std version in `tools/repl.md` to be consistent with displayed output.

reflect std/testing/asserts to std/asserts move in manual

---

references/contributing/building_from_source.md

During build, Deno depends on protoc after https://github.com/denoland/deno/pull/20178.

Add a `protoc` install step to `building_from_source`

---

runtime/kv/operations.md

- `range` is not a keyword (and can not be found in the example)
- The Note did not explain how this related to the range selector
- The example did not make explicit what is the range selector
- And a small typo that I fixed

docs(operations): Make range selector clearer

---

getting_started/first_steps.md
tools/compiler.md

We removed std/examples in https://github.com/denoland/deno_std/pull/3546, and the referenced hello world doesn't exist anymore.
This PR updates the hello world program url to https://examples.deno.land/hello-world.ts

fix: update hello world program url

---

basics/permissions.md
examples/tcp_server.md
examples/unix_cat.md
getting_started/first_steps.md
tools/bundler.md

We removed `std/examples` in https://github.com/denoland/deno_std/pull/3546 (because there are dedicated places for examples such https://examples.deno.land/ and https://github.com/denoland/examples ), and `std/examples` doesn't exist for the latest version of std anymore.
This PR pins the references to `std/examples` to the last existing version.

fix: pin std/examples to v0.198.0

---

advanced/typescript.md
basics/permissions.md
introduction.md
runtime/web_platform_apis.md
tools.md

also fixes:
- https://github.com/denoland/manual/issues/710
- https://github.com/denoland/manual/issues/712

Update footer linked content

---

references/contributing/building_from_source.md

Rewritten to make it more consistent, require most dependencies up-front. Added missing `cmake` dependency.

chore: clean up the building_from_source.md

---

getting_started/setup_your_environment.md

clarify how nvim_lsp variable is set, so it doesn't look like some missing global variable.

docs(getting started) clarify nvim setup instructions

---

node/compatibility.md

Fix list of Node compat
